/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package uppgift1;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        TimeIt classUnderTest = new TimeIt();
      //  assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
